### ISSUE TITLE
Allow command return DTO

### ISSUE THREAD

**Issue by v-maluka** [phpgears/cqrs#2]
It might be helpful to allow Command handler to return DTO object.
We often want to get result/state of executed command, created object id as example.

I suggest to replace `void` with `?DTO` in `AbstractCommandHandler`

**Comment by juliangut** [comment]
I've added a response to the PR https://github.com/phpgears/cqrs/pull/3#issuecomment-616133270

**Comment by juliangut** [comment]
Closing as PR is closed as well
